version: '3'
services:
  serve:
    build:
      context: .
    command: ["jekyll", "serve","--livereload"]
    environment:
      - JEKYLL_ENV=development
    volumes:
      - ".:/srv/jekyll"
    ports:
      - "4000:4000"   # Serve
      - "35729:35729" # Livereload
